meta_product_name: "Saas Initiative"
meta_title: "Saas Initiative | Your Saas Import/Export Platform"
meta_description: "The first SaaS solution to export your SaaS abroad efficiently and maximize your revenue from emerging countries."
meta_image: 'saasinit-tagline.png' # should exist in `app/assets/images/`
twitter_account: "@julesmaregiano"   # required for Twitter Cards
